### PR TITLE
Support src/bin subdirectories

### PR DESCRIPTION
**Pull request by stevenroose**
Solves https://github.com/RustRPM/cargo-rpm/issues/50.

This adds suppose for a directory structure in which binaries reside
in subdirectories inside src/bin. We look for a main.rs file inside each
subdirectory. Directories without main.rs cause an error.

### CODE REVIEW

**Comment by stevenroose** [comment]
I tested this successfully for my own setup over at https://github.com/stevenroose/hal/.

**Comment by tarcieri** [comment]
It might be good to use `cargo metadata` (perhaps parsed via the [`cargo_metadata` crate](https://docs.rs/cargo_metadata/)) for this

**Comment by stevenroose** [comment]
Well, I'm arguing in an issue that it would be better to just read the Cargo.toml `[[bin]]` sections.

That would be a strictly superior method than this one. But this one works for now and the current code also just fiddles with files but in a very broken way. So it's definitely an improvement.

**Comment by tarcieri** [comment]
> Well, I'm arguing in an issue that it would be better to just read the Cargo.toml [[bin]] sections.

That requires they exist, which precludes letting Cargo infer them.

I think it's better (and to me, definitely less surprising) to let Cargo compute them via either inference or `Cargo.toml`, then consume what Cargo computes, rather than making them mandatory.

**Comment by stevenroose** [comment]
Well, sure. I consider it good practice to specify your binaries in `Cargo.toml`, though. And `cargo init` also does it IIRC. So I'd be ok with just reading `Cargo.toml` and erroring "no binaries specified in `Cargo.toml`" if there are none found.

But well, up to you, this patch works currently, so I think it's strictly better than the status quo. I don't think I'll have time to make another implementation any time soon.

**Comment by tarcieri** [comment]
I pretty strongly feel targets should be enumerated using `cargo metadata`, so I'll close out this PR but would love to see a similar implementation which uses it.

**Comment by stevenroose** [comment]
I respect your decision, but it's sad that this way some functionality that is clearly needed (heck, even `cargo-rpm` itself can't be packaged using itself without this PR) will now not be available until someone makes the effort.

**Comment by tarcieri** [comment]
When I have some time I might take a look at implementing this feature using the `cargo_metadata` crate.

**Comment by stevenroose** [comment]
Honestly, it seems like this project is quite a joke if it can't even be used on itself and it refuses to accept a code change that would make it so.

I'm really wanting to use this tool to generate our Rust RPMs, but it looks like we're going to have to use something else or our local fork or something.

**Comment by tarcieri** [comment]
I would happily accept the feature if it were implemented using `cargo metadata`. I will try to get around to implementing it myself soon unless you're interested in sending a PR.

I think using `cargo metadata` for this purpose is a relatively uncontroversial best practice, whereas if I merged this PR as-is it'd be an unnecessary breaking change for most users, deviating from expected practices for cargo-based builds simply because you refuse to implement the feature properly but demand it be merged anyway. I also don't think it's too much work to implement it properly using `cargo metadata`.

> Honestly, it seems like this project is quite a joke

Please don't be insulting.

To be clear, I want this feature. This project has 11 contributors and yours is the first feature PR I have ever rejected. I hope I've made it clear why.

**Pull request closed without merging**
